test_that("hashes still work", {
  expect_output(print(zdd(1L)), 'cutsets')
  expect_output(print(zdd0() ), 'ZERO'   )
  expect_output(print(zdd1() ), 'ONE'    )
  node <- zdd(1L)
  expect_equal(p0(node), zdd0())
  expect_equal(p1(node), zdd1())
  expect_equal(zdd1(), zdd(9, p0=zdd1()))
  expect_equal(zdd(1), zdd(9, zdd(1), zdd(1)))
  expect_s3_class(node, "zdd")
  expect_error(zddr:::zdd_hash(1.2, p0 = 'not a node', p1 = zdd1()))
  expect_error(zddr:::zdd_hash(1L , p0 = 'not a node', p1 = zdd1()))
  expect_error(zddr:::zdd_hash(1L , p0 = zdd0(), p1 = 'not a node'))
  expect_error(         p0( zdd0() ) )
  expect_error(         p0( zdd1() ) )
  expect_error(         p1( zdd0() ) )
  expect_error(         p1( zdd1() ) )
  expect_error( as.integer( zdd0() ) )
  expect_error( as.integer( zdd1() ) )
})
